<?php
/*
 *@file 
 * This module privide the accordion widget for the blocks on left and right side
 */

/*
 * Implementation of hook_init()
 */
function accordion_blocks_init() {
  // including accordion related javascript and css files
  drupal_add_library('system', 'ui.accordion');
  drupal_add_js(drupal_get_path('module', 'accordion_blocks') .'/accordion_init.js');
  drupal_add_css(drupal_get_path('module', 'accordion_blocks') .'/accordion_init.css');
}

/*
 * Implementation of hook_theme_registry_alter()
 */
function accordion_blocks_theme_registry_alter(&$theme_registry) {
  // using our own block.tpl.php file.
  $theme_registry['block']['template'] = 'block';
  $theme_registry['block']['path'] = drupal_get_path('module', 'accordion_blocks');
  $theme_registry['block']['type'] = 'module';
  $theme_registry['block']['theme path'] = drupal_get_path('module', 'accordian_blocks');
  $theme_registry['block']['theme paths'] = Array();
}

/**
 * Implementation of template_preprocess_page()
 */
function accordion_blocks_preprocess_page(&$variables){
  // to add the accordian effect add this parent div for the blocks
  $regions_list = variable_get('accordion_regions',array('sidebar_first', 'sidebar_second'));
  foreach ($regions_list as $region) {
    $variables['page'][$region]['#theme_wrappers'][] = 'accordion_blocks';
  }
}

/**
 * Implementation of hook_theme()
 */
function accordion_blocks_theme() {
  return array(
    'accordion_blocks' => array(
      'render element' => 'elements', 
      'arguments' => array('elements'=>array())
    ),
  );
}

/**
 * accordion_blocks theme
 */
function theme_accordion_blocks($variables) {
  $output = '<div class="accordion_blocks_container region">';
  foreach($variables['elements'] as $key => $value) {
    if (is_array($value) && array_key_exists('#children', $value)) {
      $output .= $value['#children'];
    }
  }
  $output .= '</div>';
  return $output;
}

/**
 * Implementation of hook_menu()
 */ 
function accordion_blocks_menu() {
  //settings page
  $items['admin/settings/accordion_blocks'] = array(
    "title" => t("Accordion Blocks"),
    "description" => t("Configure the Regions to apply Accordion effect."),
    "page callback" => "drupal_get_form",
    "page arguments" => array('accordion_blocks_settings_form'),
    "access arguments" => array('administer site configuration'),
						    );
  return $items;
}

/**
 * callback for the url admin/settings/accordion_blocks
 */
function accordion_blocks_settings_form() {
  $form = array();
  global $user;
  $themes = list_themes();
  $theme = !empty($user->theme) && !empty($themes[$user->theme]->status) ? $user->theme : variable_get('theme_default', 'garland');
  $regions_list = system_region_list($theme);
  $form['accordion_regions'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Select Regions to apply Accordion effect'),
    '#options' => $regions_list,
    '#default_value' => variable_get('accordion_regions',array('sidebar_first', 'sidebar_second')),
				     );
  return system_settings_form($form);
}